# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Reliam Knowledge Base'
description:         ''
url:                 https://jjmcsorley.github.io/Public-KB/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Reliam Inc
  url:               https://twitter.com/reliam
  email:             sales@reliam.com

# Custom vars
version:             1.0.0
