# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty

# Setup
title:                ConnectWise
tagline:              'Knowledge Base'
description:          ''
url:                  https://cwkb.reliam.com
img:                  assets/img/
baseurl:              ''
paginate:             5

# Gems
gems:               [jekyll-paginate]

# About/contact
author:
  name:              Reliam Inc
  url:               https://twitter.com/reliam
  email:             sales@reliam.com

# Custom vars
version:             1.0.0
