# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ConnectWise
tagline:             'Knowledge Base'
description:         ''
url:                 https://jjmcsorley.github.io/Public-KB/
assets:              https://raw.githubusercontent.com/jjmcsorley/Public-KB/gh-pages/_assets/
baseurl:             '/CWKB'
paginate:            5

# About/contact
author:
  name:              Reliam Inc
  url:               https://twitter.com/reliam
  email:             sales@reliam.com

# Custom vars
version:             1.0.0
